# Generated by Django 2.2 on 2020-02-11 10:07

from django.db import migrations, models
import djongo.models.fields
import serviceProvider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addline_1', models.CharField(max_length=255)),
                ('addline_2', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appliedservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('comments', djongo.models.fields.ArrayModelField(model_container=serviceProvider.models.Appsercomment)),
                ('status', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appsercomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('address', djongo.models.fields.EmbeddedModelField(model_container=serviceProvider.models.Address, null=True)),
                ('services_requested', djongo.models.fields.ArrayModelField(model_container=serviceProvider.models.CustService)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_price', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('service_provider', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('spid', models.IntegerField()),
                ('service_category', models.CharField(max_length=120)),
                ('service_name', models.CharField(max_length=120)),
                ('service_desc', models.CharField(max_length=255)),
                ('service_cost', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serviceprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('services', djongo.models.fields.ArrayModelField(model_container=serviceProvider.models.ServiceList)),
                ('applied_service', djongo.models.fields.ArrayModelField(model_container=serviceProvider.models.Appliedservice)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
